### PR TITLE
Update to readme

### PR DESCRIPTION
**Pull request by usyyy**
I really enjoyed the course, and decided to pay it forward by writing a
document detailing all of the technical things I learned from each day.
 
It's a little long, so I've decided to post each day as a separate blog
on medium.

Both links have been added to the readme.

Keep up the good work!

### CODE REVIEW

**Comment by usyyy** [comment]
It looks like I modified the previous link, but I just copied and pasted her markdown and added my details (supreme laziness I know 😆 ).

**Comment by wesbos** [comment]
Thanks a ton :) Can you take the space that you added to the prev link out?

**Comment by usyyy** [comment]
Will do!

Kind regards

On 4 Aug 2017, 14:33 +0100, Wes Bos <notifications@github.com>, wrote:

Thanks a ton :) Can you take the space that you added to the prev link out?

**Comment by usyyy** [comment]
Sorry about all of these commits, as you can tell, I'm new to the game 😂

**Pull request closed without merging**
