### PR TITLE
Dg query

### PR DESCRIPTION
**Pull request by domgaulton**
This is more of a query rather than a suggested update. I was wondering, why did Wes try to add a new value (number) to the object Person (line 61) instead of just updating the age? 

Was it a mistake or is there another reason and lesson that I'm missing?

### CODE REVIEW

**Comment by palashmon** [comment]
Can you please mention this query is related to which lesson?

**Comment by domgaulton** [comment]
Hi Palashmon, It's relating to lesson 14 where Wes tries to update person from new captain object. Sorry for poor notes!

**Comment by domgaulton** [comment]
Ah so he just took it one stage further and showed rewriting as well as adding would affect both the original and the new array. 

Gotcha!

Thanks!

**Comment by palashmon** [comment]
Glad it helped! Closing this PR now.

**Pull request closed without merging**
