### PR TITLE
Fix incorrect styles

### PR DESCRIPTION
**Pull request by apopitich**
Should be 'transform: rotate()', but it will not look like in the video

### CODE REVIEW

**Comment by wesbos** [comment]
Ah yes - I was using the new rotate() syntax that isn't super well supported yet. 

Can you take the `.idea` commit out of this?

**Comment by apopitich** [comment]
Done

**Comment by apopitich** [comment]
Can I add .idea to .gitignore in other commit?

**Comment by wesbos** [comment]
This doesn't add in the transform now

**Comment by apopitich** [comment]
I don't know what else need I do =)  I took out '.idea' commit of this pull request. Now at this PR one commit left, in which i have removed incorrect styles.

**Comment by wesbos** [comment]
You'll need to add in the correct styles - otherwise you will break this demo. 

`rotate(20deg)` → `transform: rotate(20deg)`

**Comment by apopitich** [comment]
Oh! I wanted to do this way at the very beginning, but i thought it will not be like on the video. =)
I fixed it. And I removed .photo { float}  because .strip {padding-top} hadn't worked. And I hide .strip if it's empty.

**Comment by wesbos** [comment]
sorry - can you please just replace the new `rotate` with the working `transform`? I don't care to switch anything else. I hate to be a pain, but I get so much email when things change and I can't deal with it all :)

**Comment by apopitich** [comment]
Done =)

**Comment by wesbos** [comment]
thanks!

**Pull request merged**
