### PR TITLE
new stuff

### PR DESCRIPTION
**Pull request by AncyentMariner**

### CODE REVIEW

**Comment by wesbos** [comment]
Why is everyone openings PRs and closing them?

**Comment by AncyentMariner** [comment]
In my case it was meant to be a PR on my on (forked) repo. Apologies.

**Comment by wesbos** [comment]
Ohh haha! I thought I was being trolled because it happened a few times in a hour :)

**Comment by AncyentMariner** [comment]
Haha no trolling here! Can't speak for the rest of the internet, though... 
Anyways, thanks for the videos! This series is fantastic! :)

**Comment by wesbos** [comment]
Thanks Jeff! Glad you are enjoying it!

**Pull request closed without merging**
