### PR TITLE
minute and hour hand gradual update

### PR DESCRIPTION
**Pull request by stanleynguyen**
For an actual clock, the minute and hour and doesn't stay still and wait until it's the next minute/hour to move but gradually move towards the next point in accord with how the second hand moves. I think the clock will look more realistic if we can add in this.

### CODE REVIEW

**Comment by dxcqcv** [comment]
I wanna know how to keep counting the second hand when the rotation became 90.

**Comment by stanleynguyen** [comment]
@dxcqcv it got to do with the transition animation, you can try this
```js
if (secondsDegree === 90) secondHand.style.transition = 'all 0s';
else secondHand.style.transition = 'all 0.05s';
```

**Comment by dxcqcv** [comment]
@stanleynguyen thank you very much, so the only way is remove the `transition` property, I'm serious about keeping couting way heard from the vedio, but cannot find out how to do it.

**Comment by wesbos** [comment]
I appreciate the PR but I will be keeping these files the same as the videos in order to maintain consistency. Thanks though!

**Comment by soyaine** [comment]
@dxcqcv  **Counting** may mean keeping the degree increasing per `setInterval`, rather than assign the `rotate` value by calculating time. You can see the code [here](https://github.com/soyaine/JavaScript30/issues/1).

**Comment by dxcqcv** [comment]
@soyaine I'll learn it, thanks

**Pull request closed without merging**
