### PR TITLE
Fixed broken link in community content

### PR DESCRIPTION
**Pull request by onebree**

### CODE REVIEW

**Comment by wesbos** [comment]
👌

**Comment by onebree** [comment]
There is another link that is dead, but I am unsure where you want it to point to...

The listed jade lang site does not exist. The package itself was renamed to Pug for trademark reasons

https://www.npmjs.com/package/jade

https://github.com/pugjs/pug

**Comment by wesbos** [comment]
Yeah it should be updated to pug

**Comment by onebree** [comment]
OK, do you want me to submit another PR for that?

**Comment by wesbos** [comment]
Yeah!

**Pull request merged**
