### PR TITLE
Spec

### PR DESCRIPTION
**Pull request by logicmyth**

### CODE REVIEW

**Comment by wesbos** [comment]
Hey-  did you mean to PR this?

**Comment by logicmyth** [comment]
Yes, I did mean to PR.

**Comment by wesbos** [comment]
Okay - you might need a rebase and there are merge conflicts. Would be helpful to provide some description as to what this PR is about as it is fairly large.

**Comment by logicmyth** [comment]
ok, thank you. this was meant to be cloned. sorry about that.

**Pull request closed without merging**
