### PR TITLE
merging

### PR DESCRIPTION
**Pull request by cag-martinez**

### CODE REVIEW

**Comment by cag-martinez** [comment]
merging day one and day two

**Comment by Asjas** [comment]
Hey @cag-martinez 🙂 

You should be pushing your work against your own repository, you are currently doing it against the starter repo of Wes.

**Comment by cag-martinez** [comment]
I apologize I thought I was pushing to my repository. Could you give me a tip on how to fix that? Thank you!

**Comment by Asjas** [comment]
No worries 🙂 

You can `fork` the repository at the top right of Github and then change the `git remote` of the folder in your terminal to point to your forked version of this repository. That will allow you to push to your version of this repository on Github.

https://docs.github.com/en/enterprise/2.20/user/github/getting-started-with-github/fork-a-repo

**Comment by cag-martinez** [comment]
Thank you, I just cloned it and made a push to my repository everything should be working accordingly now.

**Pull request closed without merging**
