### PR TITLE
background image not working

### PR DESCRIPTION
**Pull request by Paramchoudhary**
use jpeg instead of jpg

### CODE REVIEW

**Comment by KASRA10** [comment]
aha....ok sure...vetry thanks

**Comment by Paramchoudhary** [comment]
Your mean very thanks 😀

**Comment by Paramchoudhary** [comment]
brother please merge my branch

**Comment by palashmon** [comment]
`jpg` image seems to work fine.

Link: 
- https://raw.githubusercontent.com/wesbos/JavaScript30/9e42defbccee3481f454629232b284ef580cfbc3/01%20-%20JavaScript%20Drum%20Kit/background.jpg

Output:

**Comment by Paramchoudhary** [comment]
Thanks a lot.

**Pull request closed without merging**
