### PR TITLE
Add my gh-pages and lessons to README

### PR DESCRIPTION
**Pull request by herminiotorres**
Add my links of the gh-pages and lessons to README in community content.

### CODE REVIEW

**Comment by palashmon** [comment]
Hi, thanks for your contribution.

But please submit a PR once you have completed all the 30 challenges. Looking at your repo it seems you have just completed 7 as of now. This is due to the fact that if you don't complete all challenges and leave in between then it will of no use to have a un-complete repo added in the community content section. I hope that makes sense.

Regards!

**Comment by herminiotorres** [comment]
Hi @palashmon ,

About your point of view, I think it makes sense, but if you looking, You find some links from those who have not completed it.

I can close and reopen when I finish

Regards,

**Comment by wesbos** [comment]
this is fine :)

**Comment by herminiotorres** [comment]
@wesbos thanks! <3

**Comment by palashmon** [comment]
All is cool then :+1:

**Comment by herminiotorres** [comment]
I really loved it your course! many thanks, many kudos

**Pull request merged**
