### PR TITLE
Gave a new Look to Clock #day 2 Please see

### PR DESCRIPTION
**Pull request by eshanvohra**
clock

clock

Hi i have completely changed please see it once. Hope you will like it.

### CODE REVIEW

**Comment by palashmon** [comment]
Awesome. Please create a new PR and add your name and GitHub link in the "Community #JavaScript30 Content" section inside Readme file. Thanks!

**Comment by palashmon** [comment]
Duplicate of #366. I have merged your main PR. Please now onwards add all your changes to your forked repo, instead of this main repo as this repo is meant to be 1:1 copies of what is done in the video. Thanks!

**Comment by palashmon** [comment]
Duplicate of #366.

**Comment by palashmon** [comment]
I have merged your main PR. Please now onwards add all your changes to your forked repo, instead of this main repo as this repo is meant to be 1:1 copies of what is done in the video. Thanks!

**Comment by eshanvohra** [comment]
Thanks bro. Please update the changes i suggested to main repo at Day 2 it
is in #365

**Pull request closed without merging**
